spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/URLShortener
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/URLShortener
    user: root
    password: password
    locations: classpath:db/migrations
    enabled: true
app:
  default:
    page:
      page: 0
      limits: 20
    urlPath : http://localhost:8080/
    createCount : 10
