spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/URLShortener
    username: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/URLShortener
    user: root
    password: password
    locations: classpath:db/migrations
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: yourMail
    password: yourApplicationPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
app:
  default:
    page:
      page: 0
      limits: 20
    urlPath : http://localhost:8080/
    createCount : 10
    linkDurationDays : 31
